### ISSUE TITLE
How can I get the djiBridge object 

### ISSUE THREAD

**Issue by jaganpaladin** [pktiuk/DJI_Cloud_API_minimal#1]
window.djiBridge.platformIsVerified()
How does the window object get this djiBridge object?

**Comment by pktiuk** [comment]
I don't understand your question. 

In the source code you have working example.

**Comment by jaganpaladin** [comment]
I tried running the code. When I click on login button, this is the error I'm receiving. 

"login:43 Uncaught TypeError: Cannot read properties of undefined (reading 'platformVerifyLicense')
    at HTMLButtonElement.<anonymous> (login:43:38)"
    
    I believe the line of code is this:
    
    `var token = window.djiBridge.platformVerifyLicense(
          APP_ID,
          APP_KEY,
          LICENSE
        );`
Its unable to find the djiBridge object in the "window". Are you setting this variable somewhere?

**Comment by pktiuk** [comment]
Do you open it on the dji pilot or in regular browser in pc?

**Comment by jaganpaladin** [comment]
I'm trying to open it on chrome on a laptop.

**Comment by pktiuk** [comment]
This app works only on DJI pilot
![image](https://github.com/pktiuk/DJI_Cloud_API_minimal/assets/45544416/430fc208-36f2-4db3-9828-d26e90db1311)

README directly states where you can open this app.
